# Generated by Django 4.1.7 on 2023-03-03 21:36

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import services.validators


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(upload_to=services.validators.get_path_upload_product_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp', 'gif']), services.validators.check_size_image], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, upload_to=services.validators.get_path_upload_product_sub_image, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'png', 'jpeg', 'webp']), services.validators.check_size_image], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shop.product', verbose_name='Товар'),
        ),
    ]
