export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const ALBUMS_ROUTE = '/albums'
export const ARTISTS_ROUTE = '/artists'
export const AUDIO_ROUTE = '/audio'

export const PROFILE_ROUTE = '/profile'
export const FAVORITES_ROUTE = '/favorites'
export const PLAYLISTS_ROUTE = '/plalists'
export const CHANGE_PASSWORD_ROUTE = '/change_password'